### ISSUE TITLE
"^^ " appears as "^^^"

### ISSUE THREAD

**Issue by korbinian90** [MaxGyver83/neo2-llkh#12]
Firstly, great work! The layout works generally really well!

One bug that I had is that sometimes typing "^^ " is written as "^^^". It seems to depend on the window I'm typing in. It happens every time in the Telegram app on windows (that's where this debug log is from).

Layout: neo
 symmetricalLevel3Modifiers: 0
 returnKeyAsMod3R: 0
 tabKeyAsMod4L: 0
 capsLockEnabled: 1
 shiftLockEnabled: 0
 level4LockEnabled: 0
 qwertzForShortcuts: 1
 swapLeftCtrlAndLeftAlt: 0
 swapLeftCtrlLeftAltAndLeftWin: 0
 supportLevels5and6: 1
 capsLockAsEscape: 0
 mod3RAsReturn: 0
 mod4LAsTab: 0
 debugWindow: 1

key down  sc 43 vk 0xbf 0x0 0 (M3 right)

key down  sc 20 vk 0x54 0x0 0 (A-Z)
injected   sc 20 vk 0xdc 0x10 0
injected   sc 0 vk 0x20 0x10 0
key up     sc 20 vk 0x54 0x80 0 (A-Z)

key down  sc 20 vk 0x54 0x0 0 (A-Z)
injected   sc 20 vk 0xdc 0x10 0
injected   sc 0 vk 0x20 0x10 0
key up     sc 43 vk 0xbf 0x80 0 (M3 right)
key up     sc 20 vk 0x54 0x80 0 (A-Z)

key down  sc 57 vk 0x20 0x0 0
key up     sc 57 vk 0x20 0x80 0

**Comment by korbinian90** [comment]
Hm, it might be because of the weird behaviour of this key "^". Without neo2-llkh, I have to press twice that ^^ appears.

And I found a workaround for me for Telegram. If I press "^ ", then "^^" appears.

**Comment by MaxGyver83** [comment]
That's strange.

When you type `^` as Mod3+`T`, `neo-llkh` sends first `^` and then space because the QWERTZ `^` is a dead key and only after typing/sending space, it becomes visible (as you already know from QWERTZ). When sending space, `neo-llkh.exe` only uses the virtual key code (=`0x20`) of the space bar and leaves the scan code empty (= `0`). That's this line in the debugging output:

```
injected sc 0 vk 0x20 0x10 0
```

Usually that's not a problem, but maybe it is for Chrome. I made a test version that also sets the scan code of the space bar (only when you enter `^`). Could you test it, please?
→ https://maximilian-schillinger.de/neo-llkh-caret-text.exe

**Comment by korbinian90** [comment]
Thanks for compiling it!!
Strangely, it is exactly the same behaviour, no improvement.
But it seem to be restricted to only Telegram.
I would guess that some applications just perform themselvers input manipulation for certain keys...


Einstellungen aus C:\Users\korbi\Desktop\settings.ini:
 Layout: neo
 symmetricalLevel3Modifiers: 0
 returnKeyAsMod3R: 0
 tabKeyAsMod4L: 0
 capsLockEnabled: 0
 shiftLockEnabled: 0
 level4LockEnabled: 0
 qwertzForShortcuts: 1
 swapLeftCtrlAndLeftAlt: 0
 swapLeftCtrlLeftAltAndLeftWin: 0
 supportLevels5and6: 0
 capsLockAsEscape: 0
 mod3RAsReturn: 0
 mod4LAsTab: 0
 debugWindow: 1




key down   sc 43 vk 0xbf 0x0 0 (M3 right)

key down   sc 20 vk 0x54 0x0 0 (T)
injected   sc 20 vk 0xdc 0x10 0
injected   sc 57 vk 0x20 0x10 0
key up     sc 20 vk 0x54 0x80 0 (T)
key up     sc 43 vk 0xbf 0x80 0 (M3 right)

key down   sc 43 vk 0xbf 0x0 0 (M3 right)

key down   sc 20 vk 0x54 0x0 0 (T)
injected   sc 20 vk 0xdc 0x10 0
injected   sc 57 vk 0x20 0x10 0
key up     sc 20 vk 0x54 0x80 0 (T)
key up     sc 43 vk 0xbf 0x80 0 (M3 right)

**Comment by thomasgm1971** [comment]
hello,

the nodead-caret works flawlessly in notepad. in gvim theres a very strange
behaviour, sometimes 10 keypresses and not a single caret, sometimes 3
carets per single keypress. in google chrome the character works fine in
the address bar, in any edit field in the page area its like gvim. im
writing in gmail at the moment, im not able to get a single caret in my
message. in the start menu's search field every keypress yields 2 carets
and a space. on my computer its not just telegram, its a bigger problem
with that character.

have a nice day!
thomas

Am Sa., 15. Aug. 2020 um 15:57 Uhr schrieb Korbinian Eckstein <
notifications@github.com>:

**Comment by MaxGyver83** [comment]
@korbinian90 & @thomasgm1971 : Could you check if this issue still occurs in version [v0.5.3](https://github.com/MaxGyver83/neo2-llkh/releases/tag/v0.5.3)? It might have been fixed by 51fdd3a.

**Comment by thomasgm1971** [comment]
hi max,
thank you for your great work! pr #26 and pr #12 are gone, everything
works as it should.
the "problem" is... i tested the behaviour before updating, and the
reported malfunctions were gone yet in 0.5.2 if not earlier! my
message to pr #12 is from the middle of August, i think it was the 0.3
release still. since then i circumvented the problem, and never again
tried typing "^" and "`" in vim and in web formulars.
have a nice week, thomas

Am So., 31. Jan. 2021 um 15:38 Uhr schrieb Max Schillinger
<notifications@github.com>:

**Comment by korbinian90** [comment]
I just tested the new version 0.5.3 and I couldn't reproduce the problem. Seems to work perfectly!
Good job and thank you!
